In [52]:
import numpy as np
import pandas as pd 
dataset=pd.read_csv("iris.csv")

print(dataset)

x=dataset.iloc[:,0:4].values

print(x)

y=dataset.iloc[:,4].values

print(y)

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder


labelencoder_y = LabelEncoder()  


y = labelencoder_y.fit_transform(y)  


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
#========================================================LOGISTIC REGRESSION========================================================
from sklearn.linear_model import LogisticRegression

linermodel=LogisticRegression()

linermodel.fit(x_train,y_train)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0

LogisticRegression()

In [61]:
y_pred=linermodel.predict(x_test)

#print(y_pred)

from sklearn.metrics import confusion_matrix  # Corrected here

# Assuming y_test and y_pred are already defined
cm = confusion_matrix(y_test, y_pred)


cm

array([[ 9,  0,  0],
       [ 0, 10,  1],
       [ 0,  0, 10]], dtype=int64)

In [62]:
from sklearn.metrics import accuracy_score

In [63]:
accuracy=accuracy_score(y_test,y_pred)

In [64]:
print(accuracy)

0.9666666666666667
